version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - npm test
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
