AWSTemplateFormatVersion: '2010-09-09'

Description: |
  create S3 public bucket.

Parameters:
  ServiceName:
    Type: String
    Description: upercase service name. export or import resource like ${ServiceName}AssetsS3BucketName
    AllowedPattern: "^[A-Z][a-zA-Z]+$"
  PublicBucketName:
    Type: String
    Description: public bucket name. it is recommended to use domain name.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Service Configuration
        Parameters:
          - ServiceName
      - Label:
          default: S3 Configuration
        Parameters:
          - PublicBucketName

Resources:
  AssetsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref PublicBucketName
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionExpiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 3
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketAccesslog
        LogFilePrefix: !Sub 's3/${AWS::StackName}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-bucket'

  S3BucketAccesslog:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub
        - '${AssetsS3BacketName}-accesslogs'
        - AssetsS3BacketName: !Ref PublicBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-accesslog-bucket'

Outputs:
  AssetsS3BucketName:
    Description: assets s3 bucket name
    Value: !Ref AssetsS3Bucket
    Export:
      Name: !Sub
        - ${ServiceName}AssetsS3BucketName
        - ServiceName: !Ref ServiceName
  AssetsS3BucketDomainName:
    Description: assets s3 bucket domain name
    Value: !GetAtt AssetsS3Bucket.DomainName
    Export:
      Name: !Sub
        - ${ServiceName}AssetsS3BucketDomainName
        - ServiceName: !Ref ServiceName
  AccesslogS3BucketName:
    Description: accesslog s3 bucket name
    Value: !Ref S3BucketAccesslog
    Export:
      Name: !Sub
        - ${ServiceName}AccesslogS3BucketName
        - ServiceName: !Ref ServiceName
  AccesslogS3BucketDomainName:
    Description: accesslog s3 bucket domain name
    Value: !GetAtt S3BucketAccesslog.DomainName
    Export:
      Name: !Sub
        - ${ServiceName}AccesslogS3BucketDomainName
        - ServiceName: !Ref ServiceName
