AWSTemplateFormatVersion: '2010-09-09'

Description: |
  ACM certificate for cloudFront
  create in US East (N. Virginia)us-east-1

Mappings:
  ZoneMap:
    PublicHostedZone:
      Name: gekishaman.work

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !FindInMap [ZoneMap, PublicHostedZone, Name]
      SubjectAlternativeNames:
        - !Sub
          - '*.${DomainName}'
          - DomainName: !FindInMap [ZoneMap, PublicHostedZone, Name]
      Tags:
        - Key: Name
          Value: !Sub
            - acm certificate for ${DomainName}
            - DomainName: !FindInMap [ZoneMap, PublicHostedZone, Name]
      ValidationMethod: DNS
