AWSTemplateFormatVersion: '2010-09-09'

Description: create s3 bucket

Mappings:
  S3BucketMap:
    Assets:
      Name: blog.gekishaman.work

Resources:
  AssetsS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !FindInMap ['S3BucketMap', 'Assets', 'Name']
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionExpiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 3
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketAccesslog
        LogFilePrefix: !Sub 's3/${AWS::StackName}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-bucket'

  S3BucketAccesslog:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub
        - '${AssetsS3BacketName}-accesslogs'
        - AssetsS3BacketName: !FindInMap ['S3BucketMap', 'Assets', 'Name']
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-accesslog-bucket'

Outputs:
  BlogAssetsS3BucketName:
    Description: blog assets s3 bucket name
    Value: !Ref AssetsS3Bucket
    Export:
      Name: BlogAssetsS3BucketName
  BlogAssetsS3BucketDomainName:
    Description: blog assets s3 bucket domain name
    Value: !GetAtt AssetsS3Bucket.DomainName
    Export:
      Name: BlogAssetsS3BucketDomainName
  BlogAccesslogS3BucketName:
    Description: blog accesslog s3 bucket name
    Value: !Ref S3BucketAccesslog
    Export:
      Name: BlogAccesslogS3BucketName
  BlogAccesslogS3BucketDomainName:
    Description: blog accesslog s3 bucket domain name
    Value: !GetAtt S3BucketAccesslog.DomainName
    Export:
      Name: BlogAccesslogS3BucketDomainName
