AWSTemplateFormatVersion: '2010-09-09'

Description: |
  create CodeStarConnections that connect GitHub repository.
  you must authorization access for GitHub on AWS Console after stack created.

Parameters:
  ServiceName:
    Type: String
    Description: upercase service name. resources are exported or imported like {{ServiceName}}SourceConnectionARN
    AllowedPattern: '^[A-Z][a-zA-Z]+$'
  ProviderType:
    Type: String
    Default: GitHub
    AllowedValues:
      - Bitbucket
      - GitHub
      - GitHubEnterpriseServer

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Service Configuration
        Parameters:
          - ServiceName
      - Label:
          default: CodeStar Configuration
        Parameters:
          - ProviderType

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarconnections-connection.html
  SourceConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: !Sub '${AWS::StackName}'
      ProviderType: !Ref ProviderType

Outputs:
  SourceConnection:
    Value: !Ref SourceConnection
    Export:
      Name: !Sub
        - ${ServiceName}SourceConnectionARN
        - ServiceName: !Ref ServiceName
