AWSTemplateFormatVersion: '2010-09-09'

Description: create cloudfront

Parameters:
  AcmCertificateArn:
    Type: String
    Description: ACM certificate ARN(Amazon Resource Name)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CloudFront Configuration
        Parameters:
          - AcmCertificateArn

Mappings:
  SiteMap:
    Blog:
      Name: blog

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !ImportValue BlogAssetsS3BucketDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub
                - origin-access-identity/cloudfront/${OriginAccessIdentityId}
                - OriginAccessIdentityId: !Ref CloudFrontOriginAccessIdentity
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !ImportValue BlogAccesslogS3BucketDomainName
          Prefix: !Sub CloudFront/${AWS::StackName}
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Comment: 'blog cloudfront distribution of assets'
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          DefaultTTL: 300
          MaxTTL: 300
          MinTTL: 300
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
        Aliases:
          - !Sub
            - '${Site}.${HostedZone}'
            - Site: !FindInMap ['SiteMap', 'Blog', 'Name']
              HostedZone: !ImportValue PublicHostedZoneName
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021 # recommended
          SslSupportMethod: sni-only #  server name indication (SNI)
          AcmCertificateArn: !Ref AcmCertificateArn
        HttpVersion: http2
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cloudfront'

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'blog distoributoin OAI'

  AssetsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !ImportValue BlogAssetsS3BucketName
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub
              - arn:aws:s3:::${S3BucketName}/*
              - S3BucketName: !ImportValue BlogAssetsS3BucketName
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}

  BlogRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: blog record set
      HostedZoneId: !ImportValue PublicHostedZoneId
      Name: !Sub
        - '${Site}.${HostedZone}'
        - Site: !FindInMap ['SiteMap', 'Blog', 'Name']
          HostedZone: !ImportValue PublicHostedZoneName
      Type: A
