AWSTemplateFormatVersion: '2010-09-09'

Description: create cloudfront

Parameters:
  AcmCertificateArn:
    Type: String
    Description: ACM certificate ARN(Amazon Resource Name)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CloudFront Configuration
        Parameters:
          - AcmCertificateArn

Mappings:
  ZoneMap:
    PublicHostedZone:
      Name: gekishaman.work
  SiteMap:
    Blog:
      Name: blog

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: CustomOrigin
            DomainName: !Sub
              - '${BlogBucketName}.s3-website-${AWS::Region}.amazonaws.com'
              - BlogBucketName: !ImportValue BlogBucketName
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: false
          Bucket: !Sub
            - '${BlogAccesslogBucketName}.s3.${AWS::Region}.amazonaws.com'
            - BlogAccesslogBucketName: !ImportValue BlogAccesslogBucketName
          Prefix: !ImportValue BlogBucketName
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Comment: 'blog s3 distribution'
        DefaultCacheBehavior:
          TargetOriginId: CustomOrigin
          ForwardedValues:
            QueryString: false
          DefaultTTL: 300
          MaxTTL: 300
          MinTTL: 300
          ViewerProtocolPolicy: redirect-to-https
        Aliases:
          - !Sub
            - '${Site}.${HostedZone}'
            - Site: !FindInMap ['SiteMap', 'Blog', 'Name']
              HostedZone: !FindInMap ['ZoneMap', 'PublicHostedZone', 'Name']
        ViewerCertificate:
          MinimumProtocolVersion: TLSv1.2_2021 # recommended
          SslSupportMethod: sni-only #  server name indication (SNI)
          AcmCertificateArn: !Ref AcmCertificateArn
        HttpVersion: http2
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cloudfront'

Outputs:
  CloudFrontDistributionId:
    Description: cloud front distribution id
    Value: !Ref CloudFrontDistribution
    Export:
      Name: BlogCloudFrontId
