AWSTemplateFormatVersion: '2010-09-09'

Description: create CodeBuild project for test

Parameters:
  BuildSpecFile:
    Type: String
    Description: buildSpec directory

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CodeBuild Configuration
        Parameters:
          - BuildSpecFile

Mappings:
  EnvironmentMap:
    Production:
      Name: production
  ServiceMap:
    Blog:
      Name: blog

Resources:
  TestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Location: LOCAL
        Modes:
          - LOCAL_SOURCE_CACHE
        Type: LOCAL
      Description: CodeBuild on Pull Request updated
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Value: !FindInMap [EnvironmentMap, Production, Name]
        Image: 'aws/codebuild/standard:4.0'
        Type: LINUX_GPU_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub
            - '${Env}.${ServiceName}'
            - Env: !FindInMap [EnvironmentMap, Production, Name]
              ServiceName: !FindInMap [ServiceMap, Blog, Name]
          StreamName: !Sub
            - '${ServiceName}-test-log}'
            - ServiceName: !FindInMap [ServiceMap, Blog, Name]
          Status: ENABLED
      Name: !Sub '${AWS::StackName}-test-codebuild'
      QueuedTimeoutInMinutes: 10
      ServiceRole: !ImportValue CodeBuildTestRoleArn
      Source:
        BuildSpec: !Ref BuildSpecFile
        BuildStatusConfig:
          Context: ci-test
          # TargetUrl: this build url
        Location: String
        ReportBuildStatus: true
        SourceIdentifier: !Sub
            - '${ServiceName}-codebuild-test}'
            - ServiceName: !FindInMap [ServiceMap, Blog, Name]
        Type: GITHUB
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-cloudbuild'
      TimeoutInMinutes: 10
      Triggers:
        BuildType: 'Not currently supported by AWS CloudFormation.'
        FilterGroups:
          - ExcludeMatchedPattern: false
            Pattern: 'PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED'
            Type: EVENT
        Webhook: true
