AWSTemplateFormatVersion: '2010-09-09'

Description: |
  create hosted zone

Mappings:
  ZoneMap:
    PublicHostedZone:
      Name: gekishaman.work

Resources:
  PublicHostedZone:
    Type: 'AWS::Route53::HostedZone'
    Properties:
      HostedZoneConfig:
        Comment: Public Hosted Zone
      Name: !FindInMap [ZoneMap, PublicHostedZone, Name]
      HostedZoneTags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-hosted-zone'

Outputs:
  PublicHostedZoneId:
    Description: public hosted zone id
    Value: !Ref PublicHostedZone
    Export:
      Name: PublicHostedZoneId
  PublicHostedZoneName:
    Description: public hosted zone name
    Value: !FindInMap [ZoneMap, PublicHostedZone, Name]
    Export:
      Name: PublicHostedZoneName
