AWSTemplateFormatVersion: '2010-09-09'

Description: create s3 bucket

Mappings:
  ZoneMap:
    PublicHostedZone:
      Name: gekishaman.work
  SiteMap:
    Blog:
      Name: blog

Resources:
  BlogS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub
        - '${Site}.${HostedZone}'
        - Site: !FindInMap ['SiteMap', 'Blog', 'Name']
          HostedZone: !FindInMap ['ZoneMap', 'PublicHostedZone', 'Name']
      LifecycleConfiguration:
        Rules:
          - Id: NoncurrentVersionExpiration
            Status: Enabled
            NoncurrentVersionExpirationInDays: 7
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketAccesslog
        LogFilePrefix: !Sub 's3/${AWS::StackName}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-bucket'

  S3BucketAccesslog:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketName: !Sub '${AWS::StackName}-accesslogs-${AWS::Region}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: AutoDelete
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-accesslog-bucket'

Outputs:
  PublicBucketName:
    Description: s3 public bucket name
    Value: !Ref BlogS3Bucket
    Export:
      Name: BlogBucketName
  AccesslogBucketName:
    Description: s3 accesslog bucket name
    Value: !Ref S3BucketAccesslog
    Export:
      Name: BlogAccesslogBucketName
