version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16
      # TODO: use docker image
      - npm install --location=global gatsby-cli
      - npm ci
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
