version: 0.2

env:
  parameter-store:
    GOOGLE_ANALYTICS_TRACKING_ID: /production/blog/GOOGLE_ANALYTICS_TRACKING_ID

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16
      # TODO: use docker image
      - npm install --location=global gatsby-cli
      - npm ci
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
