version: 0.2

env:
  parameter-store:
    GOOGLE_ANALYTICS_TRACKING_ID: /production/techblog/GOOGLE_ANALYTICS_TRACKING_ID

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16
      - npm ci --ignore-scripts --progress=false
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
