version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # TODO: use docker image
      - npm install -g gatsby-cli
      - npm ci
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
